# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '6 1-12/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: JohnHa0/JD_Action
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ
        run: |
          node money/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ2
        run: |
          node money/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ3
        run: |
          node money/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ4
        run: |
          node money/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}